apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-booking
spec:
  serviceName: "postgres-booking"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-booking
  template:
    metadata:
      labels:
        app: postgres-booking
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-booking-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-booking-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-booking-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-booking-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-booking-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
