apiVersion: v1
kind: Secret
metadata:
  name: postgres-booking-secret
  namespace: acl-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_DB: Ym9va2luZw== # base64 for "booking"
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtYm9va2luZy0wLnBvc3RncmVzLWJvb2tpbmc6NTQzMi9ib29raW5n
  #jdbc:postgresql://postgres-booking-0.postgres-booking:5432/booking
