apiVersion: v1
kind: Secret
metadata:
  name: postgres-booking-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_DB: Ym9va2luZw== # base64 for "booking"
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXNxbC1ib29raW5nOjU0MzIvYm9va2luZw==
  #jdbc:postgresql://postgresql-booking:5432/booking
