spring:
  application:
    name: User
  datasource:
    url: jdbc:postgresql://db:5432/userdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

booking:
  service:
    url: http://localhost:8081  # replace with actual booking service base URL
