#server:
#  port: 8080
#
#spring:
#  profiles:
#    active: docker
#
#  data:
#    redis:
#      host: redis  # Use the Redis service name defined in Docker Compose
#      port: 6379
#      timeout: 2000ms
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb  # Point to the DB service in Docker Compose
#    username: postgres
#    password: 1234
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  cache:
#    type: redis
#
#  booking:
#    service:
#      url: http://booking:8081  # Assuming the service exists
