apiVersion: v1
kind: Secret
metadata:
  name: postgres-flight-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_DB: ZmxpZ2h0 # base64 for "flight"
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXNxbC1mbGlnaHQ6NTQzMi9mbGlnaHQ=
  #jdbc:postgresql://postgresql-flight:5432/flight
