apiVersion: v1
kind: Secret
metadata:
  name: postgres-flight-secret
  namespace: acl-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_DB: ZmxpZ2h0 # base64 for "flight"
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtZmxpZ2h0LTAucG9zdGdyZXMtZmxpZ2h0OjU0MzIvZmxpZ2h0
  #jdbc:postgresql://postgres-flight-0.postgres-flight:5432/flight
