apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-secret
  namespace: acl-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_DB: dXNlcg== # base64 for "user"
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtdXNlci5hY2wtYXBwLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvdXNlcg==
  #jdbc:postgresql://postgres-user.acl-app.svc.cluster.local:5432/user
