apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 for "postgres"
  POSTGRES_DB: dXNlcg== # base64 for "user"
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXNxbC11c2VyOjU0MzIvdXNlcg==
  #jdbc:postgresql://postgresql-user:5432/user
