server:
  port: 8083

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/notifications

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    com.example.notification: DEBUG
