spring:
  application:
    name: Flight

  datasource:
    url: jdbc:postgresql://db:5432/flightdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

  cache:
    type: redis

server:
  port: 8080