spring:
  application:
    name: flight-service # ← CHANGED THIS FROM Flight TO flight-service FOR GATEWAY

  datasource:
    url: jdbc:postgresql://db:5432/flightdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis_flight
      port: 6379
      timeout: 2000ms

  cache:
    type: redis

server:
  port: 8082 # ← CHANGED THIS FROM 8080 TO 8082 FOR GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
