apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: acl-app
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA== # "root"
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ== # "example"
  URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby0wLm1vbmdvOjI3MDE3L25vdGlmaWNhdGlvbj9hdXRoU291cmNlPWFkbWlu
  # "mongodb://root:example@mongo-0.mongo:27017/notification?authSource=admin"
