spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoAutoConfiguration

  data:
    mongodb:
      uri: none

  application:
    name: booking-service # ← CHANGED THIS FROM BookingService TO booking-service FOR GATEWAY

  datasource:
    url: jdbc:postgresql://db:5432/bookingdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # ← ADD THIS
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8083 # ← CHANGED THIS FROM 8080 TO 8083 FOR GATEWAY


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
