services:
  notification-service:
    build: .
    ports:
      - "8083:8083"
    environment:
      - spring.data.mongodb.database=notification_service
      - spring.data.mongodb.uri=mongodb://root:example@mongo_db:27017/notification_service?authSource=admin
    depends_on:
      - mongo_db
      - rabbitmq

  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo_db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo_db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # App connection
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
