version: '3.8'

services:
  flightservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flightservice
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    container_name: flight_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=flightdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: