apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-service
  namespace: acl-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway-service
  template:
    metadata:
      labels:
        app: apigateway-service
    spec:
      containers:
        - name: apigateway-service
          image: mohamedmohey/acl-apigw
          ports:
            - containerPort: 80
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SERVER_PORT
              value: "80"
            - name: SPRING_MAIN_WEB_APPLICATION_TYPE
              value: reactive

            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: user-service
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: http://user-service:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: Path=/api/users/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: flights-route
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: http://flight-service:8081
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: Path=/api/flights/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
              value: bookings-route
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
              value: http://booking-service:8082
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
              value: Path=/api/bookings/**

            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_ID
              value: notifications-route
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_URI
              value: http://notification-service:8083
            - name: SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0
              value: Path=/api/notifications/**
