version: '3.8'

services:
  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userservice
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: user_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=userdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

#version: '3.8'
#
#services:
#  userservice:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: userservice
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    restart: always
#
#  db:
#    image: postgres
#    container_name: user_postgres
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=1234
#      - POSTGRES_DB=userdb
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    restart: always
#
#volumes:
#  pgdata:
