version: '3.8'

services:
  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userservice
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/userdb
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15
    container_name: user_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=userdb
    restart: always


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
